feat: Document LitTemplate disabled annotation support
vaadin/flow-and-components-documentation pull request #1371
Opened 2020-10-13 11:35 UTC by caalador

Document limitation in LitTemplate not supporting
the disabled attribute for a id-mapped component.

part of vaadin/flow#9152

2020-10-13 15:20 UTC, joheriks requested changes

2020-10-13 15:20 UTC, joheriks commented on documentation/polymer-templates/tutorial-template-mapped-components-limitations.asciidoc
> +This will throw a `IllegalArgumentException` with the message
```suggestion
This will throw an `IllegalArgumentException` with the message
```

2020-10-13 15:20 UTC, joheriks commented on documentation/polymer-templates/tutorial-template-mapped-components-limitations.asciidoc
> +LitTemplate doesn't support using the `disabled` attribute for an id-mapped component.
Could perhaps hint what will happens if a component is `disabled` anyway in the template. Does the parser throw an exception or will it silently cause inconsistent state.

2020-10-14 05:36 UTC, caalador commented on documentation/polymer-templates/tutorial-template-mapped-components-limitations.asciidoc
> +This will throw a `IllegalArgumentException` with the message
Done.

2020-10-14 06:04 UTC, joheriks submitted a review, later dismissed

2020-10-14 06:15 UTC, denis-anisimov reviewed
Original Flow PR related question : what's about Polymer ?
Should we say anything here about behavior for `disabled`  in polymer tempaltes.
I'm pretty sure that the current behavior should be reverted and may be `disabled`  should become `disabled` property on the server side. And I believe this should be said somewhere in docs.....

2020-10-14 09:26 UTC, caalador commented
Added note for polymer and updated the exception message as per changes to the functionality.

2020-10-14 09:43 UTC, denis-anisimov approved these changes

2020-10-14 11:08 UTC, merged